export enum ORDER_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum ORDER_TYPE {
  DELIVERY = "DELIVERY",
  PICKUP = "PICKUP",
}

export enum PAYMENT_STATUS {
  COMPLETED = "COMPLETED",
  PENDING = "PENDING",
}

export enum PAYMENT_METHOD {
  CASH_ON_DELIVERY = "CASH_ON_DELIVERY",
  ESEWA = "ESEWA",
}
